from tkinter import *
window=Tk()
window.title("Hello Python")
window.config(bg="grey")
lbl=Label(window,text="Enter Name",fg="Blue",bg="grey")
lbl.place(x=60,y=50)
txtfld=Entry(window,text="Enter Your Name",bd=5)
txtfld.place(x=80,y=150)
btn=Button(window,text="Submit",fg="green",bg="pink")
btn.place(x=80,y=100)
window.geometry("300x200")
window.mainloop()